version: '3.5'

services:
  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
  app:
    image: nextcloud:fpm
    volumes:
      - type: volume
        source: nextcloud_NFS
        target: /var/www/html
        volume:
          nocopy: true
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    depends_on:
      - db
  web:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes: 
      - type: volume
        source: nextcloud_NFS
        target: /var/www/html
        volume:
          nocopy: true
    depends_on:
      - nextcloud
    configs:
      - source: nginx_config_ext
        target: /etc/nginx/nginx.conf
        
configs:
  nginx_config_ext:
    external: true
    
volumes:
  db:
  nextcloud:
    external: true
  nextcloud_NFS:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas02.macworx.de,nolock,soft,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/zfs_pool01/nextcloud_storage"
  nginx:

