version: '3.5'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
  app:
    image: nextcloud:fpm
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    depends_on:
      - db
  web:
    image: nginx:alpine
    ports:
      - 8080:80
    links:
      - nextcloud
    volumes:
      - nextcloud:/var/www/html
    restart: always
    depends_on:
      - nextcloud
    configs:
      - source: nginx_config_ext
        target: /etc/nginx/nginx.conf
        
configs:
  nginx_config_ext:
    external: true
    
volumes:
  db:
  nextcloud:
  nginx:
