version: '3.5'

services:
  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud_NFS:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    depends_on:
      - db
      
volumes:
  db:
  nextcloud_NFS:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas02.macworx.de,nolock,soft,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/zfs_pool01/nextcloud_storage"
  nginx:
