
version: '3.2'

services:
  db:
    image: mariadb
    ports:
      - 8306:3306
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
  app:
    image: nextcloud:apache
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    ports:
      - 8080:80
    volumes:
      - nextcloud_local_special:/var/www/html
    depends_on:
      - db
volumes:
  db:
  nextcloud_local_special:
  nextcloud_NFS:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas02.macworx.de,nolock,soft,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/zfs_pool01/nextcloud_storage"
